name: Quality test

on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - "**"

jobs:
    quality:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: true
            matrix:
                node-version: [lts/*, current]
                os: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm test
